ACCOUNTS = ["GCHLHDBOKG2JWMJQBTLSL5XG6NO7ESXI2TAQKZXCXWXB5WI2X6W233PR"]
VERSION = "0.1.0"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
SIGNING_KEY = "GCHLHDBOKG2JWMJQBTLSL5XG6NO7ESXI2TAQKZXCXWXB5WI2X6W233PR"
TRANSFER_SERVER = "https://janchor.alfredpay.io/sep6"
TRANSFER_SERVER_SEP0024 = "https://janchor.alfredpay.io/sep24"
WEB_AUTH_ENDPOINT = "https://janchor.alfredpay.io/auth"
KYC_SERVER = "https://janchor.alfredpay.io/sep12"
DIRECT_PAYMENT_SERVER = "https://janchor.alfredpay.io/sep31"
ANCHOR_QUOTE_SERVER = "https://janchor.alfredpay.io/sep38"

[[CURRENCIES]]
code = "USDC"
issuer = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
status = "test"
is_asset_anchored = true
anchor_asset_type = "fiat"
desc = "A test USDC issued by Circle."

[DOCUMENTATION]
ORG_NAME = "AlfredPay"
ORG_URL = "https://alfredpay.io"
ORG_DESCRIPTION = "Powering LATAM's Digital Economy"
ORG_LOGO = "https://assets-global.website-files.com/63d1babbeaa9f7ea41da982f/645d7469833989a850e73e42_logo_white.png"
ORG_SUPPORT_EMAIL = "email@your.org"
